apiVersion: v2
type: application
name: lubelogger
description: |
  LubeLogger is a web-based vehicle maintenance and fuel mileage tracker
home: https://lubelogger.com
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/lubelogger/icon.png
version: 1.4.1
appVersion: "v1.5.3"
sources:
  - https://github.com/hargata/lubelog
keywords:
  - vechicle
  - maintenance
  - dashboard
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: added
      description: '**lubelogger:** set only selector labels on volumes'
      links:
      - name: 'GitHub Issue #258'
        url: https://github.com/anza-labs/charts/issues/258
      - name: Commit 2ad8a8c
        url: https://github.com/anza-labs/charts/commit/2ad8a8c8d9484ac2f191779c1a27707b58883797
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
