apiVersion: v2
type: application
name: pocket-id
description: |
  pocket-id is a simple and easy-to-use OIDC provider that allows users to authenticate
  with their passkeys to your services.
home: https://pocket-id.org
version: 1.3.0
appVersion: "v1.4.1"
sources:
  - https://github.com/pocket-id/pocket-id
keywords:
  - idp
  - oidc
  - passkeys
  - sso
annotations:
  artifacthub.io/category: security
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: added
      description: '**pocket-id:** add local-ipv6 configuration'
      links:
      - name: 'GitHub Issue #162'
        url: https://github.com/anza-labs/charts/issues/162
      - name: Commit a6ad7b6
        url: https://github.com/anza-labs/charts/commit/a6ad7b6c902cfd3f79d03e601795bec6ac0b4bc5
    - kind: added
      description: '**pocket-id:** add otel configuration'
      links:
      - name: 'GitHub Issue #163'
        url: https://github.com/anza-labs/charts/issues/163
      - name: Commit 6ae1358
        url: https://github.com/anza-labs/charts/commit/6ae1358b3b0c52e323043aa69d7dac8127fe9d86
    - kind: changed
      description: '**deps:** update ghcr.io/pocket-id/pocket-id docker tag to v1.4.1'
      links:
      - name: 'GitHub Issue #161'
        url: https://github.com/anza-labs/charts/issues/161
      - name: Commit c5efac7
        url: https://github.com/anza-labs/charts/commit/c5efac76469e315263357c34e387722eff3b214e
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
