apiVersion: v2
type: application
name: pocket-id
description: |
  pocket-id is a simple and easy-to-use OIDC provider that allows users to authenticate
  with their passkeys to your services.
home: https://pocket-id.org
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pocket-id/icon.png
version: 1.7.6
appVersion: "v1.16.0"
sources:
  - https://github.com/pocket-id/pocket-id
keywords:
  - idp
  - oidc
  - passkeys
  - sso
annotations:
  artifacthub.io/category: security
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update docker.io/litestream/litestream docker tag to v0.5.9'
      links:
      - name: 'GitHub Issue #338'
        url: https://github.com/anza-labs/charts/issues/338
      - name: Commit 1b0152d
        url: https://github.com/anza-labs/charts/commit/1b0152d87a7f6b9a4ce2414fbbedc745cb5416eb
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
