apiVersion: v2
type: application
name: pyoci
description: |-
  Publish and install private python packages using OCI/docker registries.
home: https://pyoci.com
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pyoci/icon.jpg
version: "1.0.2"
appVersion: "v0.1.37"
sources:
  - https://github.com/AllexVeldman/pyoci
keywords:
  - oci-registry
  - docker
  - pyoci
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update ghcr.io/allexveldman/pyoci docker tag to v0.1.37'
      links:
      - name: 'GitHub Issue #337'
        url: https://github.com/anza-labs/charts/issues/337
      - name: Commit c8fc974
        url: https://github.com/anza-labs/charts/commit/c8fc9748f6318e34c5ef494537cd7872d8fa0043
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
